image:
  file: .gitpod/Dockerfile

ports:
  # NginX
  - port: 3449
    onOpen: open-preview
  
  # Mailhog web interface
  - port: 8025
    onOpen: ignore

  # Mailhog postfix port
  - port: 1025
    onOpen: ignore

  # Postgresqk default port
  - port: 5432
    onOpen: ignore